[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[phases.setup]
nixPkgs = ["nodejs@18", "npm"]

[[phases.commands]]
name = "Install dependencies"
command = "npm install --legacy-peer-deps"

[[phases.commands]]
name = "Build"
command = "npm run build"